name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      # - name: Install Node.js, NPM and Yarn
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 'lts/*'
      #     cache: 'yarn'
      # - name: Yarn Install
      #   run: yarn

      # - name: Build Electron app
      #   run: yarn electron-builder --win --ia32 --publish never
      
      # - name: Show Build
      #   run: |
      #     ls dist
      #     ls node_modules/usb/build/Release

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: electron-quick
      #     path: dist/electron-quick-start Setup 1.0.0.exe

      - name: Inf2Cat
        run: |
          $Env:Path += ';C:\Program Files (x86)\Windows Kits\10\bin\x86'
          Inf2Cat.exe /v /os:XP_X86,Vista_X86,Vista_X64,7_X86,7_X64,8_X86,8_X64,6_3_X86,6_3_X64,10_X86,10_X64 /driver:./driver

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: driver
          path: driver